<?php ?>
<script type="text/javascript">

<?php $category = Mage::registry("current_category");?>
<?php
$formKey = '';

try{
    $formkey_html = $this->getBlockHtml('formkey');
    $pattern = '/.*form_key.*value=\"([^\"]+)\"/s';
    if (preg_match($pattern, $formkey_html, $match)){
        if ($match){
         $formKey = $match[1];
        }
    }
} catch (Exception $e){
    Mage::logException($e);
}

?>

if(typeof expertSiteConf == 'undefined' || expertSiteConf == null) {
    var expertSiteConf = {
        currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>",
        formkey:"<?php echo $formKey; ?>"
        <?php if (isset($category)) { ?>
            ,category:"<?php echo $category->getName(); ?>"
        <?php } ?>
    };
}

//Add website and store id
<?php 
setcookie("webId",Mage::app()->getWebsite()->getId());
setcookie("storeId",Mage::app()->getStore()->getId());
setcookie("currency",Mage::app()->getStore()->getCurrentCurrencyCode());
setcookie("merchantId", Mage::getStoreConfig('expertrec/general/mid'));
?>

/* * * DON'T EDIT BELOW LINE * * */

(function(){var domain=window.location.hostname.replace(/\./g,""),ea=document.createElement('script');ea.type='text/javascript';ea.async=true;ea.src='//d3qm5o86jyjko6.cloudfront.net/rec/expertrec_'+domain+'.js';var m=document.getElementsByTagName('script')[0];m.parentNode.insertBefore(ea,m)})();var _eaq=_eaq || [];function expertApi(){if(window.expertrec_true){var args=Array.prototype.slice.call(arguments);window.ea_apispec[args[0]](args.slice(1,args.length))}else{_eaq.push(arguments);}}


</script>
<?php  ?>